Fix es thousand separator
vtex-apps/format-currency pull request #15
Opened 2021-02-03 14:50 UTC by rodrigo-olivera

#### What problem is this solving?

   The default "es" currency format is not following the normal conventions of comma separators for thousands
   The comma separator should be each 3 integers like ($1,876.00)
   This validation ensures that the issue on "es" currency locale by UNICODE has a workaround
   * https://unicode-org.atlassian.net/browse/CLDR-13762
   * https://unicode-org.atlassian.net/projects/CLDR/issues/CLDR-13265?filter=allissues&orderby=created%20DESC&keyword=spanish
   

#### How should this be manually tested?
Just adding items to the cart until the total is >= $1,000.00
[Workspace](https://commafix--tiendamx.myvtex.com/)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshot without the fix
<img width="1680" alt="Screen Shot 2021-02-03 at 8 41 36" src="https://user-images.githubusercontent.com/65255533/106762869-e3eba500-65fb-11eb-8574-29feffd66596.png">

#### Screenshot with the fix
<img width="1680" alt="Screen Shot 2021-02-03 at 8 40 36" src="https://user-images.githubusercontent.com/65255533/106762888-e8b05900-65fb-11eb-904a-4ff927d07502.png">

#### Type of changes

✔️ | Type of Change
---|---
✔️ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

2021-02-03 14:54 UTC, rodrigo-olivera reviewed
Add changelog

2021-02-03 15:00 UTC, rodrigo-olivera commented
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

2021-02-03 15:00 UTC, rodrigo-olivera commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2021-02-03 17:57 UTC, igorbrasileiro requested changes

2021-02-03 17:57 UTC, igorbrasileiro commented on react/formatCurrency.ts
> +    const numberParts: NumberParts = parts.reduce((obj, item) => ({ ...obj, [item.type]: item.value }), <NumberParts>{});
Take care, parts can have multiple objects of the same type. Example:
```tsx
const parts = intl.formatNumberToParts(1900, { currency: 'USD', style: 'currency' })
/*
parts value = [{type: "currency", value: "US$"}
{type: "literal", value: " "},
{type: "integer", value: "1"},
{type: "group", value: "."},
{type: "integer", value: "900"},
{type: "decimal", value: ","},
{type: "fraction", value: "00"}
]
*/

numberParts = parts.reduce(...)
/* 
numberParts value = {
currency: "US$"
decimal: ","
fraction: "00"
group: "."
integer: "900"
literal: " "
}
*/
```

Look that `numberParts.integer` value should be 1900, but the value is 900.

2021-02-03 17:57 UTC, igorbrasileiro commented on react/formatCurrency.ts
> +  if (culture.language == "es") {
Just a suggestion
```suggestion
  if (culture.language === "es") {
```

2021-02-03 18:04 UTC, igorbrasileiro commented
Apparently isn't working properly in the workspace.

2021-02-05 15:16 UTC, rodrigo-olivera commented on react/formatCurrency.ts
> +    const numberParts: NumberParts = parts.reduce((obj, item) => ({ ...obj, [item.type]: item.value }), <NumberParts>{});
@igorbrasileiro 

Just tested this comments and got this results:

```
const parts = intl.formatNumberToParts(1900, { currency: 'MXN', style: 'currency' })
/*
[0: {type: "currency", value: "$"}
1: {type: "integer", value: "1900"}
2: {type: "decimal", value: "."}
3: {type: "fraction", value: "00"}]
*/
```

Take in account that this Fix only works wen the integer is equal to 4 because its the only case that has the issue according to UNICODE reports and specification.

If the validation is is correct `culture.language = es & "integer" = 4` this fix resolves exacly this issue, nothing else, seems to me working, also in the workspace... as shown in the screenshots, is there something more specific that is not working?

2021-02-05 15:18 UTC, rodrigo-olivera commented on react/formatCurrency.ts
> +    const numberParts: NumberParts = parts.reduce((obj, item) => ({ ...obj, [item.type]: item.value }), <NumberParts>{});
Using the same configuration as in your example i have the same result, seems to be working...

```
const parts = intl.formatNumberToParts(1900, { currency: 'USD', style: 'currency' })
0: {type: "currency", value: "USD"}
1: {type: "literal", value: " "}
2: {type: "integer", value: "1900"}
3: {type: "decimal", value: "."}
4: {type: "fraction", value: "00"}
```

2021-02-05 15:28 UTC, igorbrasileiro commented on react/formatCurrency.ts
> +    const numberParts: NumberParts = parts.reduce((obj, item) => ({ ...obj, [item.type]: item.value }), <NumberParts>{});
Nice! can you share an workspace with this changes?

2021-02-05 15:44 UTC, rodrigo-olivera commented on react/formatCurrency.ts
> +    const numberParts: NumberParts = parts.reduce((obj, item) => ({ ...obj, [item.type]: item.value }), <NumberParts>{});
Im testing here: https://commafix--tiendamx.myvtex.com/

2021-02-08 13:50 UTC, igorbrasileiro commented on react/formatCurrency.ts
> +    const numberParts: NumberParts = parts.reduce((obj, item) => ({ ...obj, [item.type]: item.value }), <NumberParts>{});
I was testing and I saw this problem. Integer length isn't 4 and it's return the wrong value, should be 51,700.00, right?!
![image](https://user-images.githubusercontent.com/15680320/107228362-59d87d80-69fb-11eb-89be-97cca4dda988.png)

2021-02-09 18:18 UTC, rodrigo-olivera commented on react/formatCurrency.ts
> +    const numberParts: NumberParts = parts.reduce((obj, item) => ({ ...obj, [item.type]: item.value }), <NumberParts>{});
For me this scenary is correct but i think im going to implement more bulletproof validations. let me go back on this approach with you over the week

2021-06-03 18:38 UTC, Git-the-Sanz commented
Hey! @rodrigo-olivera What's the status on this? We are facing the same issue in a couple of es-AR stores.

2021-07-03 00:15 UTC, rodrigo-olivera commented
> Hey! @rodrigo-olivera What's the status on this? We are facing the same issue in a couple of es-AR stores.

Hi Git-the-Sanz its being reviewed by the Product team

2021-07-07 02:04 UTC, lariciamota requested changes

2021-07-07 02:04 UTC, lariciamota commented on react/utils.ts
> +        //apply decimal precision if its defined
```suggestion
        //apply decimal precision if it's defined
```

2021-07-07 17:29 UTC, igorbrasileiro requested changes

2021-07-07 17:37 UTC, igorbrasileiro commented
I don't think that's good we have to rewrite the intl parser. I liked the first solution, which was using the intl parser result then replace appends `,` between each group of 3 numbers. By doing that we can cover all solutions, look at examples:

1. 1.00
2. 100.00
3. 1,000.00
4. 100,000.00
5. 1,000,000.00

2021-08-09 18:53 UTC, victorhmp commented
Closing this since it seems to be stale.
@rodrigo-olivera feel free to reopen it if you plan on getting back to it :)

2021-08-09 18:53 UTC, closed without merging